### ISSUE TITLE
请教个问题？

### ISSUE THREAD

**Issue by renwfy** [coder-pig/WechatHelper#2]
自定添加群成员为好友，我参考了你的写法，但是这个需求有些问题

**Comment by coder-pig** [comment]
什么问题？

**Comment by renwfy** [comment]
解析 “群所有成员” 界面，拿到的成员，要么不全，要么重复

**Comment by coder-pig** [comment]
你那边解析的逻辑是怎么样的？无障碍我能想到的就是解析一次页面，然后滚屏，但是会出现你说的问题（不全和重复），如果你会，能用Xposed的话可以Hook联系人列表 hook 下com.tencent.mm.ui.contact.AddressUI.a 拿到群成员列表。或者像我一样用itchat这个微信网页端来获取所有群成员，然后写个正则提取下就好。

**Comment by renwfy** [comment]
现在用的是无障碍模式，滚屏的时候不是刚好一屏，所以出现不全或重复，然后列表去重，好像不大可行，正打算加Xposed
